using System.Collections.Generic;

namespace Diacritics.AccentMappings
{
    public partial class VietnameseAccentsMapping : IAccentMapping
    {
        private static readonly IDictionary<char, string> MappingDictionary = new Dictionary<char, string>
        {
			{ 'à', "a" },
			{ 'á', "a" },
			{ 'â', "a" },
			{ 'ã', "a" },
			{ 'è', "e" },
			{ 'é', "e" },
			{ 'ê', "e" },
			{ 'ì', "i" },
			{ 'í', "i" },
			{ 'ò', "o" },
			{ 'ó', "o" },
			{ 'ô', "o" },
			{ 'õ', "o" },
			{ 'ù', "u" },
			{ 'ú', "u" },
			{ 'ý', "y" },
			{ 'ă', "a" },
			{ 'ĩ', "i" },
			{ 'ũ', "u" },
			{ 'ơ', "o" },
			{ 'ư', "u" },
			{ 'ạ', "a" },
			{ 'ả', "a" },
			{ 'ấ', "a" },
			{ 'ầ', "a" },
			{ 'ẩ', "a" },
			{ 'ẫ', "a" },
			{ 'ậ', "a" },
			{ 'ắ', "a" },
			{ 'ằ', "a" },
			{ 'ẳ', "a" },
			{ 'ẵ', "a" },
			{ 'ặ', "a" },
			{ 'ẹ', "e" },
			{ 'ẻ', "e" },
			{ 'ẽ', "e" },
			{ 'ế', "e" },
			{ 'ề', "e" },
			{ 'ể', "e" },
			{ 'ễ', "e" },
			{ 'ệ', "e" },
			{ 'ỉ', "i" },
			{ 'ị', "i" },
			{ 'ọ', "o" },
			{ 'ỏ', "o" },
			{ 'ố', "o" },
			{ 'ồ', "o" },
			{ 'ổ', "o" },
			{ 'ỗ', "o" },
			{ 'ộ', "o" },
			{ 'ớ', "o" },
			{ 'ờ', "o" },
			{ 'ở', "o" },
			{ 'ỡ', "o" },
			{ 'ợ', "o" },
			{ 'ụ', "u" },
			{ 'ủ', "u" },
			{ 'ứ', "u" },
			{ 'ừ', "u" },
			{ 'ử', "u" },
			{ 'ữ', "u" },
			{ 'ự', "u" },
			{ 'ỳ', "y" },
			{ 'ỵ', "y" },
			{ 'ỷ', "y" },
			{ 'ỹ', "y" }
        };

        public IDictionary<char, string> Mapping { get { return MappingDictionary; } }
    }
}